apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mynginxdeployment
  labels:
    app: myapp 
    type: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      type: front-end
  template:
      metadata:
        name: mynginxpod
        labels: 
          app: myapp
          type: front-end
      spec:
        containers:
        - name: mynginxcontainer
          image: nginx:1.14.2
          ports:
           - containerPort: 80 