apiVersion: apps/v1
kind: Deployement
metadata: 
  name: mynginxapp
  labels:
    app: myapp 
    type: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      type: frontend
  template:
    spec:
      metadata:
        name: mynginxpod
        labels: 
          app: myapp
          type: frontend
      spec:
        containers:
        - name: mynginxcontainer
          image: nginx:1.14.2
          ports:
          - containerPort: 80 