apiVersion: v1
kind: Pod
metadata: 
  name: mynginxpod
  labels:
    app: myapp
    type: frontend
spec:
  containers:
  - name: mynginxcontainer
    image: nginx:1.14.2
    ports:
     - containerPort: 80