apiVersion: v1 
kind: Service
metadata:
  name: myserviceapp
spec: 
  selector:
    app: myapp
    type: front-end
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 80
  type: LoadBalancer

